name: "Publish swift package"

on: push

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

  release:
    needs: build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: rymndhng/release-on-push-action@master
        id: release
        with:
          bump_version_scheme: minor
          tag_prefix: v
          release_name: "<RELEASE_VERSION>"

      - name: Access tag name of current workflow
        run: |
          echo "RELEASE_VERSION=${{ steps.release.outputs.version }}" >> $GITHUB_ENV
          echo "RELEASE_TAG=${{ steps.release.outputs.tag_name }}" >> $GITHUB_ENV
          echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Create release branch on package repo
        uses: GuillaumeFalourd/create-other-repo-branch-action@v1
        with:
          repository_owner: 'c0de-wizard'
          repository_name: 'tvmaniac-swift-packages'
          new_branch_name: ${{ env.RELEASE_VERSION }}
          access_token: ${{ secrets.API_TOKEN_GITHUB}}

